### ISSUE TITLE
Nombre en comentario

### ISSUE THREAD

**Issue by nbxandresvejar** [jonathan-jackob/emprenD#1]
El comentario muestra el id del usuario: 19/05/21 13:39:45 - usuario 12, colocar el nombre

**Comment by nbxandresvejar** [comment]
![Uploading image.png…]()
 sigue mostrando usuario, en lugar del nombre del usuario.

**Comment by jonathan-jackob** [comment]
Ya subí el cambio, espero que se halla corregido, ya que es por la manera de obtener el usuario, que no es la ideal, ya que creo que la ideal debería de ser obteniendo el usuario junto con los comentarios, quise agregar el with en la api  para obtener la relación de comentarios y su usuario, pero no me funciono :/, quedo atento a cualquier otro comentario :)
